In [2]:
import numpy as np
import random

In [3]:
a = np.zeros(4)
b = np.random.random_sample((4,2))
# a.shape


In [4]:
b

array([[0.04296597, 0.08918268],
       [0.47300928, 0.5486687 ],
       [0.29129432, 0.28381894],
       [0.37018534, 0.61058775]])

In [5]:
c = np.arange(3.)
c

array([0., 1., 2.])

In [6]:
d = np.random.rand(4)
d

array([0.29780932, 0.88389066, 0.19107585, 0.63342284])

In [7]:
arr = np.arange(10)
print(arr)
for i in range(len(arr)):
  if i+1==1:
    sux="st"
  elif i+1==2:
    sux = "nd"
  elif i+1==3:
    sux = "rd"
  else:
    sux = "th"
  print(f"{arr[i]} is the {i+1}{sux} element")

[0 1 2 3 4 5 6 7 8 9]
0 is the 1st element
1 is the 2nd element
2 is the 3rd element
3 is the 4th element
4 is the 5th element
5 is the 6th element
6 is the 7th element
7 is the 8th element
8 is the 9th element
9 is the 10th element


In [15]:
# Array Slicing
arr[0:9:2] #Even
arr[1:9:2] #Odd
arr[0:9:4]

array([0, 4, 8])

In [16]:
a = np.array([1, 2, 3, 4])
print(f"a(original) : {a}")
b = -a #Negattion
print(f"b(Negation) : {b}")
sum = np.sum(a) #returns a scalar
print(f"sum : {sum}")
c = a**2
print(f"c(Squares) : {c}")


a(original) : [1 2 3 4]
b(Negation) : [-1 -2 -3 -4]
sum : 10
c(Squares) : [ 1  4  9 16]


In [25]:
# Vector Ops
#   Addition and Substraction
a = np.array([[1,2,3,4],[4,3,2,1]])
b=  np.array([[2,4,6,8],[1,3,5,7]])

print(f"Add : {a+b}")
print(f"Substract: {a-b}")


Add : [[ 3  6  9 12]
 [ 5  6  7  8]]
Substract: [[-1 -2 -3 -4]
 [ 3  0 -3 -6]]


In [26]:
# Scalar Multiply
print(a*4) #Constant Multiply

[[ 4  8 12 16]
 [16 12  8  4]]


In [29]:
# Vector Product (Dot Product)
print(np.dot(a,b.T)) #Transpose of B (2,4) (4,2)

[[60 50]
 [40 30]]
