In [2]:
import numpy as np
import time

In [3]:
# Vector Creation - Creating a Vector with Zeros
a = np.zeros(4);
print(a, a.shape, a.dtype)

[0. 0. 0. 0.] (4,) float64


In [4]:
# Vector Creation -  Creating a vector with random values (Float)
a = np.random.random_sample(4)
print(a, a.shape, a.dtype)

[0.88494605 0.12556539 0.87834808 0.73346678] (4,) float64


In [8]:
# Vector Creation -  Creating a vector with random values (Integers)
# a = np.random.random_integers(4) - Is deprecated
a = np.random.randint(1, 4+1, size=4) #Include size, if not then it returns a random number
print(a, a.shape, a.dtype)

[2 3 3 4] (4,) int64


In [9]:
# Vector Creation -  Creating a vector with the first n whole numbers
a = np.arange(4)
print(a, a.shape, a.dtype)

[0 1 2 3] (4,) int64


In [11]:
# Vector Creation -  Creating a vector manually
a = np.array([1, 4, 2, 4, 5])
print(a, a.shape, a.dtype)
a = np.array([1, 4, 2, 4, 5.]) #to make into float - enter float point entries
print(a, a.shape, a.dtype)

[1 4 2 4 5] (5,) int64
[1. 4. 2. 4. 5.] (5,) float64


In [13]:
# Indexing in Numpy array

a = np.arange(10) #0,1,2 . . 9
print(a)

# Accessing the first element
print(a[0])

# Accessing the last element
print(a[9]) #This is method 1 : Note not 10 .. as indexing starts from 0
print(a[-1]) #This is method 2

[0 1 2 3 4 5 6 7 8 9]
0
9
9


In [16]:
# Vector Slicing

a = np.arange(10)
print(a)

# [start, stop, step] - start and stop are indices, step is an integer
c = a[1:8:1]
print(c)

c = a[2:7:2]
print(c)

# Accessing all elements after 3
c = a[3:]
print(c)

#Acessing all element  till 3
c = a[:3]
print(c)

# Acessing all elements
c = a[:]
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


In [18]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a)
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


In [19]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [22]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]
